### ISSUE TITLE
Not working with navigationController?.hidesBarsOnSwipe = true

### ISSUE THREAD

**Issue by JFERSD** [xiongxiong/ActionCell#1]
Hi @xiongxiong,

When I set `self.navigationController?.hidesBarsOnSwipe = true` cell options won't show. If I disable it, it works.

**Comment by xiongxiong** [comment]
Hi @perroyverde 

You can use a custom NavigationController, like this one:

`class NavigationController: UINavigationController, UIGestureRecognizerDelegate {
    
    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        return true
    }
}`

**Comment by JFERSD** [comment]
It worked like a charm. Thanks @xiongxiong !
