### ISSUE TITLE
Unable to press buttons behind ActionCell Wrapper

### ISSUE THREAD

**Issue by JFERSD** [xiongxiong/ActionCell#2]
Hi again @xiongxiong,

I've encountered a new issue. I'm unable to press buttons inside a cell because the ActionCell Wrapper view is at the front.

Is there any way or workaround to achieve this? 

Thanks.

**Comment by xiongxiong** [comment]
@perroyverde 

It's difficult to resolve it now, I need sometime to make changes. And I made some changes to the control, you don't need custom NavigationController now.

**Comment by JFERSD** [comment]
Cool. Please let me now if you manage to solve the buttons problem. Thank you.

**Comment by xiongxiong** [comment]
@perroyverde 

Hi, I've resolved the problem, you can try again.

**Comment by JFERSD** [comment]
@xiongxiong 
Awesome! It works perfectly. Awesome library btw!
