### ISSUE TITLE
Different behaviour in different tableViewSections

### ISSUE THREAD

**Issue by JFERSD** [xiongxiong/ActionCell#3]
Hi again,

I'm in trouble trying to have one tableview section without ActionCell and another section with it.
I've tried to wrap only one section but all cells keep showing actions. 

I'm using `dequeueReusableCell()` . I've also tried setting delegate to nil, and setting wrapper as a custom cell property and setting it to nil in `prepareForReuse()` without success.

Any ideas on how to show some cells with ActionCell and other without it? 

Thanks in advance!

**Comment by xiongxiong** [comment]
@perroyverde Sorry, I can't reproduce the problem, make sure you use latest version of the control, and if the problem still exists, tell me more details.

**Comment by JFERSD** [comment]
Hi, @xiongxiong . Thank you for your dedication.

I'm using just one custom cell with one reuse identifier for a tableView with multiple sections. 

When I do the cell `wrap()` in `cellForRowAt` or in `willDisplay cell`, the cells of other sections that aren't wrapped start to behave as an ActionCell too.

Maybe i'm missing something but my code is pretty straightforward

```
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {

    let cell = self.tableView.dequeueReusableCell(withIdentifier: SurveysCell.REUSE_ID, for: indexPath) as! SurveysCell

    // 1. Create cell actions
    let actionDeleteLeft = self.createCellAction(...)
    let actionDeleteRight = self.createCellAction(...)

    // 2. If my datasource object is of desired type I wrap the cell

    if indexPath.section == sections.teacher.rawValue {
    
            if survey.type == Survey.sType.xxxxx {
                let wrapper = ActionCell()
                wrapper.delegate = self
                wrapper.animationStyle = .ladder
                wrapper.wrap(cell: cell, actionsLeft: [actionDeleteLeft], actionsRight: [actionDeleteRight])
            }
        }
...

return cell
}
```

**Comment by xiongxiong** [comment]
@perroyverde I've modified the demo to reproduce the problem, but it works fine with custom cell & dequeueReusableCell, you can checkout the demo and help me to modify it to reproduce the problem, thank you.

<img width="278" alt="jietu20170209-064125" src="https://cloud.githubusercontent.com/assets/3443704/22761156/859345e0-ee94-11e6-9426-f8e6810f60a4.png">

**Comment by JFERSD** [comment]
Hey, @xiongxiong

I've forked ActionCell: [fork](https://github.com/perroyverde/ActionCell)

I was able to reproduce the bug in the example. When you scroll the list up and down, when cells are drawn and redrawn, they start to behave erratically. Those that shouldn't have wrapper sometimes show the same actions as others that have wrapper in other sections.

Please, let me know if there is anything wrong on how I'm wrapping the cells or if it is a bug. 

Thank you!

**Comment by xiongxiong** [comment]
Hi, @perroyverde  I'm terribly sorry, it's really a defect, I should provide a way to let the user clear the wrapper view, because the wrapper is a private property. I've added a method for UITableViewCell, you should check the latest version, and call it in prepareForReuse method, like this:

`
override func prepareForReuse() {
        super.prepareForReuse()
        clearActionsheet()
    }
`

Thank you for your feedback!

**Comment by JFERSD** [comment]
Awesome! 🎉 

I don't have any merit, but I'm glad to help somehow at ActionCell improvement 😄
